model_list:
  - model_name: veille-produit
    litellm_params:
      model: openai/moonshot-v1-32k
      api_key: "sk-NKlYxY9X61Dvf2hq6a9cgNXmxH3eIYTd2WG9xZOjwU34HoyG"
      api_base: "https://api.moonshot.cn/v1"
  - model_name: gestion-privee
    litellm_params:
      model: ollama/llama3.1
      api_base: "http://ollama:11434"
